# Generated by Django 4.2.11 on 2024-05-08 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payapp', '0002_transaction_currency_useraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.AddField(
            model_name='transaction',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='received_currency',
            field=models.CharField(choices=[('GBP', 'Pounds £'), ('USD', 'Dollars $'), ('EUR', 'Euros €')], default='GBP', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sent_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sent_currency',
            field=models.CharField(choices=[('GBP', 'Pounds £'), ('USD', 'Dollars $'), ('EUR', 'Euros €')], default='GBP', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
